services:
  - type: web
    name: closet-cleanup
    env: node
    buildCommand: npm install && npm run build:ssr
    startCommand: node dist/closet-cleanup/server/main.js
    plan: free
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri-here
      - key: PORT
        value: 3000
